### ISSUE TITLE
Pass the actual error instead of just a string as part of promise rejections

### ISSUE THREAD

**Issue by skodamarthi** [intuit/user-data-for-fraud-prevention#31]
Currently for the errors in getDeviceLocalIPAsString function https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L13  we are only passing some error strings and not the actual stacktrace for the error. Construct an object that includes both the string and the actual error and pass it as a param to the reject. This will help consumers to understand what the actual error incase if there is an error.

**Comment by benknoble** [comment]
Hey @skodamarthi, I think I would like to work on this. I've identified the `reject` calls you referenced as

- https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L20
- https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L28
- https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L35
- https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L51

Questions I have:
1. Some of the rejections are caused by explicit error-capturing; for those where we detect some kind of invalid state (`NO_IP_FOUND`, `WEBRTC_UNSUPPORTED_BROWSER`), what should the actual error be?
2. What should the object look like? I was thinking `{message: string, err: Object}` or something similar.
3. Where should I document these changes? Is this function depended on internally, or is it more of a provided API function by the package? This seems like it would be a breaking change if the latter, as any one who handles these error strings needs to change their error handling.

**Comment by reubenae** [comment]
@benknoble agreed, it looks like the only place this would require a change is here: https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L28

I'm not entirely convinced about the value here. It definitely would be a breaking change - which is not an issue, just something for us to keep in mind when we release it.

My uncertainty stems from not being sure that the stack trace is actually of any value to a consumer. It becomes useful if you want to debug and fix the issue, but if you're doing that then pulling the code locally and adding logs seems like it will be the same amount of effort.

Thoughts?

**Comment by skodamarthi** [comment]
@benknoble and @reubenae Thanks for your comments! My thought was to do like this:
catch((e) => {
            reject({message: "CREATE_CONNECTION_ERROR", error: e})
}

Just replacing the string with an object that also includes the error. That would help the users to see the actual error other than just the string we are sending, so that they can get a quick understanding of what exactly is happening without having to do any additional changes to add logs etc; locally to understand the issue. Does that make sense?

**Comment by benknoble** [comment]
>  the only place this would require a change is here:

I think https://github.com/intuit/user-data-for-fraud-prevention/blob/4919173553cc993485ded740c75e731a6ce742fe/src/js/common/browserInfoHelper.js#L51 would also benefit; and then it would probably be nice for all the errors in `reject` to have a uniform interface, so I would argue to change all of them (and find a sensible value for the other two).

> stack trace is actually of any value to a consumer
> pulling the code locally and adding logs seems like it will be the same amount of effort

Depends on who the "consumer" is. I've found it's easier to troubleshoot and debug when a bug-report has a stack-trace, which you would get virtually for free by virtue of it being available to whomever files the issue. Then *you* are the consumer. This is practically independent of whether the person filing the bug is a developer consuming your package or a user interacting with something that uses it, though generally the latter need to be asked to provide the error messages.

So, the question then becomes: do it now or do it later? Once you run into an issue and have to add those logs, it'll be a chore compared to the "real" problem of debugging the issue.

---

@skodamarthi makes sense. See my comments on unifying the error type: shall we provide just `{message: "..."}` when there is no error?

**Comment by reubenae** [comment]
> Depends on who the "consumer" is. I've found it's easier to troubleshoot and debug when a bug-report has a stack-trace, which you would get virtually for free by virtue of it being available to whomever files the issue. Then _you_ are the consumer. This is practically independent of whether the person filing the bug is a developer consuming your package or a user interacting with something that uses it, though generally the latter need to be asked to provide the error messages.

Okay, I absolutely love this. You have convinced me :) 

On the other points:

- Definitely we need a uniform interface from the function. `{message: "xyz", err: null|undefined|stacktrace}` is good for me.
- If we're going to do this, the sooner we do it the better. Fewer places to update, fewer consumers to update their consumed version.

**Comment by benknoble** [comment]
Alright, I'll draft a quick PR on the code, and we can work on docs/updates/whatever else from there.

**Comment by skodamarthi** [comment]
Great! Thank you! @benknoble Yes! All the places where reject is called has to be changed to follow the same pattern.
