### ISSUE TITLE
Remove global utils file

### ISSUE THREAD

**Issue by reubenae** [intuit/user-data-for-fraud-prevention#34]
We created a global utils file so we could easily inject mocked global objects (like document, window etc).

This was purely to help with testing. Instead we should acces the globals where we want them, and update the tests to use jest's global object.

See https://github.com/intuit/user-data-for-fraud-prevention/blob/master/tests/unit/common/browserInfoHelper.test.js#L229 for an example.

**Comment by sarahdahippo** [comment]
Hi! I am a vGHC OSD contributor :) What do you mean by accessing the globals where we want them? And which tests do we update? Thank you!

**Comment by skodamarthi** [comment]
Hi @sarahdahippo! Thanks for reaching out. As part of this fix, you need to get rid of src/js/common/globalsUtil.js file and make the code changes necessary. Also you need to fix the tests in browserInfoHelper.test.js and mtdFraudPrevention.test.js, as they would start failing after removing GlobalUtils.js file. To fix the tests, you can directly directly stub jest's global object instead of globalsUtil.

**Comment by jitinmaher** [comment]
Added Pr for this issue here: https://github.com/intuit/user-data-for-fraud-prevention/pull/75

**Comment by skodamarthi** [comment]
@jitinmaher  CI build was failing due to test failures: https://app.circleci.com/pipelines/github/intuit/user-data-for-fraud-prevention/167/workflows/6094951a-4260-4c73-a45d-477558ccb23f/jobs/169. Can you please fix the tests and raise another PR?
